### ISSUE TITLE
No redirection from plain-http to secure https

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/infrastructure#1]
```
$ curl -i http://studentrobotics.org
curl: (7) Failed to connect to studentrobotics.org port 80: Connection refused
```

Prior to the move to this incarnation of our infrastructure this used to work, but now fails.

**Comment by jimmythompson** [comment]
I would expect that to be handled by this: 

https://github.com/srobo/infrastructure/blob/master/src/load_balancer.tf#L12

Weird.

**Comment by PeterJCLaw** [comment]
Yeah, I too had assumed that that line would do this.

**Comment by jimmythompson** [comment]
<img width="679" alt="Screenshot 2019-07-23 at 22 18 48" src="https://user-images.githubusercontent.com/653864/61748335-dc590800-ad97-11e9-967f-3e0e9ccf28c0.png">

**Comment by PeterJCLaw** [comment]
```
$ curl -i http://www.studentrobotics.org
HTTP/1.1 307 Temporary Redirect
Cache-Control: no-cache
Content-length: 0
Location: https://www.studentrobotics.org/
```

:tada: 

Shame it's 307 as this should be a permanent redirect, also that it's manual in the UI, but oh well.
