### ISSUE TITLE
www. form of the domain presents security warning rather than redirecting

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/infrastructure#2]
```
$ curl -i https://www.studentrobotics.org
curl: (51) SSL: certificate subject name (studentrobotics.org) does not match target host name 'www.studentrobotics.org'
```

Prior to the move to this incarnation of our infrastructure this used to work, but now fails.

This also means that a number of git repo clones, including those on `patience` no longer work as our HTTPS git clone urls all use the `www.` form of the url.

**Comment by jimmythompson** [comment]
This looks like it's because the certificate doesn't contain any subdomains including `www.`. I'll take a look, but feel free to give it a try.

**Comment by PeterJCLaw** [comment]
Yeah, I think we might need a cert for both. I'm not sure what happens if you present a `www.foo.tld` cert for `foo.tld`, but I think I'd expect that to error similarly to how this is (otherwise it would allow subdomains to impersonate the root).

**Comment by jimmythompson** [comment]
It looks like it's working? 🤷‍♀

**Comment by PeterJCLaw** [comment]
What did you change?

**Comment by jimmythompson** [comment]
I amended the certificate and added www.
